steps:
##Build the docker image from the code using the docker file
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image', '.' ]
  
## Run a sonarscan
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args:
  - '-X'
  - '-Dsonar.organization=digiarchs'
  - '-Dsonar.projectKey=Digiarchs_docker-test'
  - '-Dsonar.sources=.'
  - '-Dsonar.host.url=https://sonarcloud.io'
  secretEnv: ['SONAR_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
    env: 'SONAR_TOKEN'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run','deploy','first-service','--image', 
    'us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image', 
    '--region','us-central1','--platform','managed','--allow-unauthenticated','--timeout','300']
images: ['us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image']
tags: ['cloud-builders-community']


