steps:
##Check the source code on sonarcloud
##For quality gates
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args: 
  - '-Dsonar.organization=digiarchs'
  - '-Dsonar.projectKey=Digiarchs_docker-test'
  - '-Dsonar.sources=.'
  - '-Dsonar.host.url=https://sonarcloud.io'
  secretEnv: ['SONAR_TOKEN']

#[Start Docker_build]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/${PROJECT_ID}/digiarchs-docker-repo/hellodocker-image', '.' ]
#[End Docker_build]

#[Start Docker_push to artifactory repository]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/${PROJECT_ID}/digiarchs-docker-repo/hellodocker-image']
#[End Docker_push to artifactory repository]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run','deploy','first-service','--image', 
    'us-east1-docker.pkg.dev/${PROJECT_ID}/digiarchs-docker-repo/hellodocker-image', 
    '--region','us-central1','--platform','managed','--allow-unauthenticated','--timeout','300']

#images: ['us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
    env: 'SONAR_TOKEN'
tags: ['cloud-builders-community']

