--- 
availableSecrets: 
  secretManager: 
    - 
      env: SONAR_TOKEN
      versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
images: 
  - us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image
name: gcr.io/cloud-builders/docker
steps: 
  - 
    args: 
      - "-Dsonar.organization=digiarchs"
      - "-Dsonar.projectKey=Digiarchs_docker-test"
      - "-Dsonar.sources=."
      - "-Dsonar.host.url=https://sonarcloud.io"
    name: "gcr.io/$PROJECT_ID/sonar-scanner:latest"
    secretEnv: 
      - SONAR_TOKEN
tags: 
  - cloud-builders-community
  - 
    args: 
      - push
      - "us-east-1-docker.pkg.dev/${PROJECT_ID}/digiarchs-docker-repo/hellodocker-image"
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - build
      - "-t"
      - "us-east1-docker.pkg.dev/${PROJECT_ID}/digiarchs-docker-repo/hellodocker-image"
      - "."
    name: gcr.io/cloud-builders/docker


#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#  entrypoint: gcloud
#  args: ['run','deploy','first-service','--image', 
#    'us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image', 
#    '--region','us-central1','--platform','managed','--allow-unauthenticated','--timeout','300']
#images: ['us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image']
#tags: ['cloud-builders-community']
#availableSecrets:
#  secretManager:
#  - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
#    env: 'SONAR_TOKEN'


