steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image:tag1', '.' ]
    images:
    - 'us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image:tag1'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
       "run",
       "deploy",
       "first-service",
       "--image",
       "us-east1-docker.pkg.dev/dev-environment-orgwebsite/digiarchs-docker-repo/hellodocker-image:tag1",
       "--region",
       "us-central1",
       "--platform",
       "managed",
       "--allow-unauthenticated",
     ]


